Welcome to a competition powered by AutoDSC for Data Science Challenges! By Prof. Manoel Gadi!

PLEASE DO NOT RENAME THIS FILE!


Simply run this code and start competing today in the competion: 6aQ6IxU7Va

6aQ6IxU7Va details:
 - Description / Descripción: FRAUD MODELLING CHALLENGE - Predict which Credit Card Application is legitimate and which belongs to a fraudster instead.
 - Maximum number of daily attempts / Número máximo de intentos diarios: 1000
 - Creation date / Fecha de creación: 2020-06-10 11:36:52
 - Starting date / Fecha de inicio: 2021-12-08 12:00:00
 - Ending date / Fecha de fin: 2021-12-20 23:59:00
 - Minimum time between prediction submissions / Tiempo mínimo entre envíos de predicciones: 10

Of couse, to win the competition you should improve the starting model! So let's get to work!

In [1]:
print ("IMPORTING LIBRARIES...")
import pandas as pd


print ("LOADING DATASETS...")
try: # reading train csv from local file
    df_train = pd.read_csv("mfalonso__6aQ6IxU7Va__train.csv")
    df_train.head()
except: # reading train csv from the internet if it is the first time
    import urllib
    csv_train = urllib.request.urlopen("http://manoelutad.pythonanywhere.com/static/uploads/mfalonso__6aQ6IxU7Va__train.csv")
    csv_train_content = csv_train.read()
    with open("mfalonso__6aQ6IxU7Va__train.csv", 'wb') as f:
            f.write(csv_train_content)
    df_train = pd.read_csv("mfalonso__6aQ6IxU7Va__train.csv")

    
try: # reading test csv from local file
    df_test = pd.read_csv("mfalonso__6aQ6IxU7Va__test.csv")
    df_test.head()
except: # reading test csv from the internet if it is the first time
    import urllib
    csv_test = urllib.request.urlopen("http://manoelutad.pythonanywhere.com/static/uploads/mfalonso__6aQ6IxU7Va__test.csv")
    csv_test_content = csv_test.read()
    with open("mfalonso__6aQ6IxU7Va__test.csv", 'wb') as f:
            f.write(csv_test_content)
    df_test = pd.read_csv("mfalonso__6aQ6IxU7Va__test.csv")

IMPORTING LIBRARIES...
LOADING DATASETS...

In [2]:
df_train.head()

,Unnamed: 0,id,ib_var_1,ib_var_2,ib_var_3,ib_var_4,ib_var_5,ib_var_6,ib_var_7,ib_var_8,...,if_var_73,if_var_74,if_var_75,if_var_76,if_var_77,if_var_78,if_var_79,if_var_80,if_var_81,ob_target
0,0,1,0,1,0,0,1,1,0,0,...,0.800,0,6,5,0.500000,9.4634,5140.0,0.766667,1,0
1,1,2,0,1,0,0,0,1,0,0,...,0.925,5,8,5,0.400000,7.6341,2570.0,0.700000,4,0
2,2,3,0,0,0,0,1,1,0,0,...,0.800,3,10,6,0.700000,11.1707,5140.0,0.666667,2,0
3,3,4,0,1,0,1,1,1,0,0,...,0.825,5,5,6,0.433333,8.0488,1028.0,0.766667,3,0
4,4,5,0,0,0,0,0,1,0,0,...,0.800,0,11,5,0.700000,5.5854,5140.0,0.733333,3,0

In [3]:
df_test.head()

,Unnamed: 0,id,ib_var_1,ib_var_2,ib_var_3,ib_var_4,ib_var_5,ib_var_6,ib_var_7,ib_var_8,...,if_var_73,if_var_74,if_var_75,if_var_76,if_var_77,if_var_78,if_var_79,if_var_80,if_var_81,contract_date
0,0,1,0,1,0,0,1,0,0,0,...,0.775,1.0,10.0,11.0,0.666667,NaN,5140.000000,0.666667,3,20-Sep-12
1,1,2,1,0,0,0,1,1,0,0,...,0.750,0.0,8.0,10.0,0.600000,12.9024,5140.000000,0.733333,0,24-Sep-12
2,2,3,0,0,0,0,1,1,0,0,...,0.725,0.0,8.0,6.0,0.700000,NaN,2570.000000,0.766667,1,19-Sep-12
3,3,4,0,1,0,1,1,1,0,0,...,0.925,2.0,7.0,5.0,0.566667,15.5366,2056.000000,0.833333,0,20-Sep-12
4,4,5,1,0,0,1,1,1,0,0,...,0.925,0.0,10.0,7.0,0.333333,17.8293,4728.799805,0.633333,2,25-Sep-12

In [4]:
df_train = df_train.drop(columns=['Unnamed: 0', 'id'])

In [5]:
df_test.drop(columns=['contract_date', 'Unnamed: 0'], inplace=True)

In [6]:
print ("STEP 1: DOING MY TRANSFORMATIONS...")
df_train = df_train.fillna((df_train.mean()))
df_test = df_test.fillna((df_test.mean()))

X_test = df_test.drop(columns=["id"])


#from sklearn.impute import KNNImputer
#knn based imputation for categorical variables
#imputer = KNNImputer(n_neighbors=2)
#df_train = imputer.fit_transform(['if_var_78'])
# print the completed dataframe

STEP 1: DOING MY TRANSFORMATIONS...

In [7]:
df_train.head()

,ib_var_1,ib_var_2,ib_var_3,ib_var_4,ib_var_5,ib_var_6,ib_var_7,ib_var_8,ib_var_9,ib_var_10,...,if_var_73,if_var_74,if_var_75,if_var_76,if_var_77,if_var_78,if_var_79,if_var_80,if_var_81,ob_target
0,0,1,0,0,1,1,0,0,0,0,...,0.800,0,6,5,0.500000,9.4634,5140.0,0.766667,1,0
1,0,1,0,0,0,1,0,0,0,0,...,0.925,5,8,5,0.400000,7.6341,2570.0,0.700000,4,0
2,0,0,0,0,1,1,0,0,0,0,...,0.800,3,10,6,0.700000,11.1707,5140.0,0.666667,2,0
3,0,1,0,1,1,1,0,0,0,0,...,0.825,5,5,6,0.433333,8.0488,1028.0,0.766667,3,0
4,0,0,0,0,0,1,0,0,0,0,...,0.800,0,11,5,0.700000,5.5854,5140.0,0.733333,3,0

In [8]:
df_test.head()

,id,ib_var_1,ib_var_2,ib_var_3,ib_var_4,ib_var_5,ib_var_6,ib_var_7,ib_var_8,ib_var_9,...,if_var_72,if_var_73,if_var_74,if_var_75,if_var_76,if_var_77,if_var_78,if_var_79,if_var_80,if_var_81
0,1,0,1,0,0,1,0,0,0,0,...,5,0.775,1.0,10.0,11.0,0.666667,9.733613,5140.000000,0.666667,3
1,2,1,0,0,0,1,1,0,0,0,...,6,0.750,0.0,8.0,10.0,0.600000,12.902400,5140.000000,0.733333,0
2,3,0,0,0,0,1,1,0,0,0,...,7,0.725,0.0,8.0,6.0,0.700000,9.733613,2570.000000,0.766667,1
3,4,0,1,0,1,1,1,0,0,0,...,4,0.925,2.0,7.0,5.0,0.566667,15.536600,2056.000000,0.833333,0
4,5,1,0,0,1,1,1,0,0,0,...,5,0.925,0.0,10.0,7.0,0.333333,17.829300,4728.799805,0.633333,2

In [9]:
df_train.dtypes

ib_var_1       int64
ib_var_2       int64
ib_var_3       int64
ib_var_4       int64
ib_var_5       int64
              ...
if_var_78    float64
if_var_79    float64
if_var_80    float64
if_var_81      int64
ob_target      int64
Length: 82, dtype: object

In [15]:
print ("STEP 3: DEVELOPING THE MODEL...")
X_train = df_train.drop(columns=["ob_target"])
y_train = df_train["ob_target"]



#from sklearn.linear_model import LogisticRegression
#clf = LogisticRegression(random_state=0, solver='lbfgs')
#fitted_model = clf.fit(X_train, y_train)
#pred_train = fitted_model.predict_proba(X_train)[:,1]
#pred_test  = fitted_model.predict_proba(X_test)[:,1]

# import Random Forest classifier

import time 

from sklearn.ensemble import RandomForestClassifier
for max_depth in range (21,22):
    for n_estimators in range (100, 10000, 100):
        for random_state in range (100, 10000, 100):
            rfc = RandomForestClassifier(max_depth = max_depth*8, n_estimators=n_estimators*7,  random_state=random_state*10, max_features="log2", n_jobs = -1)
            rfc.fit(X_train, y_train)
            y_pred = rfc.predict(X_train)

            #print ("STEP 5: SUBMITTING THE RESULTS... DO NOT CHANGE THIS PART!")
            import requests
            from requests.auth import HTTPBasicAuth
            pred_test = rfc.predict_proba(X_test)[:,1]
            print(pred_test)


            df_test['pred'] = pred_test
            df_test['id'] = df_test.iloc[:,0]
            df_test_tosend = df_test[['id','pred']]


            filename = "df_test_tosend.csv"

            df_test_tosend.to_csv(filename, sep=',')
            url = 'http://manoelutad.pythonanywhere.com/uploadpredictions/6aQ6IxU7Va'
            files = {'file': (filename, open(filename, 'rb')),
                 'ipynbcode': ('6aQ6IxU7Va.ipynb', open('6aQ6IxU7Va.ipynb', 'rb'))}



            #rsub = requests.post(url, files=files)

            rsub = requests.post(url, files=files, auth=HTTPBasicAuth("margaridapm", "sha256$bkpQgZOa$f401ae21f46569c8d1c5d8ca134e30a22b0fc649b8bab3b2cb69f043d5f5e227"))
            resp_str = str(rsub.text)

            print ("RESULT SUBMISSION:{} for max_depth = {} for n_estimators={}".format(resp_str, max_depth, n_estimators*7))

            time.sleep(30)

STEP 3: DEVELOPING THE MODEL...
[0.13428571 0.13428571 0.06       ... 0.11       0.09       0.09571429]
RESULT SUBMISSION:Competition / competición: 6aQ6IxU7Va - gini = 0.48951815636004037 for max_depth = 21 for n_estimators=700
[0.15142857 0.12714286 0.05285714 ... 0.10428571 0.07142857 0.09857143]
RESULT SUBMISSION:<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
 for max_depth = 21 for n_estimators=700
[0.13142857 0.13571429 0.05857143 ... 0.09285714 0.08428571 0.09857143]
RESULT SUBMISSION:<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
 for max_depth = 21 for n_estimators=700
[0.13428571 0.16714286 0.05       ... 0.11142857 0.09428571 0.08285714]
RESULT SUBMISSION:Competition / competición: 6aQ6IxU7Va - gini = 0.4903384042366381 for max_depth = 21 for n_estimators=700
[0.15142857 0.15285714 0.07142857 ... 0.11428571 0.10428571 0.08285714]
RESULT SUBMISSION:<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
 for max_depth = 21 for n_estimators=700
[0.14571429 0.15       0.05285714 ... 0.09571429 0.08428571 0.08      ]
RESULT SUBMISSION:<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
 for max_depth = 21 for n_estimators=700
[0.14428571 0.14857143 0.05428571 ... 0.10142857 0.07714286 0.09142857]
RESULT SUBMISSION:Competition / competición: 6aQ6IxU7Va - gini = 0.49704941820164694 for max_depth = 21 for n_estimators=700
[0.15285714 0.14       0.06571429 ... 0.07714286 0.08285714 0.09714286]
RESULT SUBMISSION:Competition / competición: 6aQ6IxU7Va - gini = 0.49317923455854484 for max_depth = 21 for n_estimators=700
[0.14285714 0.17       0.06714286 ... 0.10571429 0.09428571 0.10714286]
RESULT SUBMISSION:Competition / competición: 6aQ6IxU7Va - gini = 0.48844028133346873 for max_depth = 21 for n_estimators=700
[0.14285714 0.17857143 0.06       ... 0.09857143 0.10285714 0.10428571]
RESULT SUBMISSION:<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
 for max_depth = 21 for n_estimators=700
[0.12142857 0.14714286 0.08142857 ... 0.09285714 0.08       0.07714286]
RESULT SUBMISSION:<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
 for max_depth = 21 for n_estimators=700
[0.13571429 0.15571429 0.05428571 ... 0.12142857 0.1        0.09428571]
RESULT SUBMISSION:<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
 for max_depth = 21 for n_estimators=700
[0.14571429 0.13857143 0.05428571 ... 0.11142857 0.07857143 0.09285714]
RESULT SUBMISSION:Competition / competición: 6aQ6IxU7Va - gini = 0.49577167996007354 for max_depth = 21 for n_estimators=700
[0.14571429 0.16428571 0.06428571 ... 0.09285714 0.08857143 0.08714286]
RESULT SUBMISSION:Competition / competición: 6aQ6IxU7Va - gini = 0.4901281435133411 for max_depth = 21 for n_estimators=700
[0.16       0.14714286 0.06571429 ... 0.08       0.11142857 0.11857143]
RESULT SUBMISSION:Competition / competición: 6aQ6IxU7Va - gini = 0.48796430650930245 for max_depth = 21 for n_estimators=700
[0.16285714 0.14142857 0.04714286 ... 0.10857143 0.08714286 0.07428571]
RESULT SUBMISSION:<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
 for max_depth = 21 for n_estimators=700
[0.13857143 0.13857143 0.07571429 ... 0.09428571 0.09142857 0.09571429]
RESULT SUBMISSION:<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
 for max_depth = 21 for n_estimators=700
[0.13142857 0.13571429 0.06428571 ... 0.12285714 0.11142857 0.09714286]
RESULT SUBMISSION:Competition / competición: 6aQ6IxU7Va - gini = 0.49428945738870045 for max_depth = 21 for n_estimators=700
[0.15       0.13714286 0.05       ... 0.10285714 0.07857143 0.10714286]
RESULT SUBMISSION:Competition / competición: 6aQ6IxU7Va - gini = 0.4910546770302866 for max_depth = 21 for n_estimators=700
[0.16142857 0.15428571 0.07571429 ... 0.1        0.07428571 0.09714286]
RESULT SUBMISSION:Competition / competición: 6aQ6IxU7Va - gini = 0.4970216915128607 for max_depth = 21 for n_estimators=700
[0.13428571 0.15571429 0.07142857 ... 0.1        0.10571429 0.07857143]
RESULT SUBMISSION:<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
 for max_depth = 21 for n_estimators=700
[0.14428571 0.15714286 0.05428571 ... 0.11142857 0.08714286 0.09      ]
RESULT SUBMISSION:<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
 for max_depth = 21 for n_estimators=700
[0.12857143 0.13285714 0.06142857 ... 0.11714286 0.08571429 0.07285714]
RESULT SUBMISSION:Competition / competición: 6aQ6IxU7Va - gini = 0.5015168809323562 for max_depth = 21 for n_estimators=700
[0.15       0.14428571 0.05857143 ... 0.13857143 0.08571429 0.07285714]
RESULT SUBMISSION:<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
 for max_depth = 21 for n_estimators=700
[0.15428571 0.16142857 0.07       ... 0.10571429 0.10285714 0.08571429]
RESULT SUBMISSION:Competition / competición: 6aQ6IxU7Va - gini = 0.48758653037458743 for max_depth = 21 for n_estimators=700
[0.13857143 0.13       0.05571429 ... 0.09428571 0.09714286 0.08142857]
RESULT SUBMISSION:<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
 for max_depth = 21 for n_estimators=700
[0.13142857 0.16285714 0.06428571 ... 0.09714286 0.11428571 0.07857143]
RESULT SUBMISSION:<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
 for max_depth = 21 for n_estimators=700
[0.14       0.15285714 0.04428571 ... 0.09       0.11571429 0.10142857]
RESULT SUBMISSION:<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
 for max_depth = 21 for n_estimators=700
[0.14285714 0.13571429 0.04857143 ... 0.09142857 0.07857143 0.11285714]
RESULT SUBMISSION:Competition / competición: 6aQ6IxU7Va - gini = 0.4806386842761947 for max_depth = 21 for n_estimators=700
[0.14285714 0.13714286 0.05       ... 0.09714286 0.09714286 0.09285714]
RESULT SUBMISSION:<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
 for max_depth = 21 for n_estimators=700
[0.12714286 0.15857143 0.06714286 ... 0.08       0.08285714 0.08714286]
RESULT SUBMISSION:<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
 for max_depth = 21 for n_estimators=700
[0.14428571 0.16142857 0.06285714 ... 0.11428571 0.09428571 0.07142857]
RESULT SUBMISSION:Competition / competición: 6aQ6IxU7Va - gini = 0.4869349531881071 for max_depth = 21 for n_estimators=700
[0.13571429 0.14857143 0.05857143 ... 0.12285714 0.10571429 0.10428571]
RESULT SUBMISSION:Competition / competición: 6aQ6IxU7Va - gini = 0.499256000517565 for max_depth = 21 for n_estimators=700
[0.15857143 0.16428571 0.06428571 ... 0.1        0.09285714 0.09714286]
RESULT SUBMISSION:Competition / competición: 6aQ6IxU7Va - gini = 0.48639197219937325 for max_depth = 21 for n_estimators=700
[0.16       0.16142857 0.06571429 ... 0.09285714 0.08       0.10571429]
RESULT SUBMISSION:<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
 for max_depth = 21 for n_estimators=700
[0.13571429 0.14142857 0.05714286 ... 0.11857143 0.09857143 0.09142857]
RESULT SUBMISSION:Competition / competición: 6aQ6IxU7Va - gini = 0.4893125167515411 for max_depth = 21 for n_estimators=700
[0.13714286 0.16428571 0.05571429 ... 0.08428571 0.09428571 0.10142857]
RESULT SUBMISSION:Competition / competición: 6aQ6IxU7Va - gini = 0.49546668638342295 for max_depth = 21 for n_estimators=700
[0.13857143 0.16       0.05857143 ... 0.10857143 0.09       0.09428571]
RESULT SUBMISSION:<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
 for max_depth = 21 for n_estimators=700
[0.14571429 0.15857143 0.04428571 ... 0.09428571 0.10857143 0.06428571]
RESULT SUBMISSION:<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
 for max_depth = 21 for n_estimators=700
[0.14857143 0.16285714 0.07571429 ... 0.11142857 0.09857143 0.09428571]
RESULT SUBMISSION:Competition / competición: 6aQ6IxU7Va - gini = 0.48619904065656794 for max_depth = 21 for n_estimators=700
[0.15714286 0.15285714 0.05571429 ... 0.10428571 0.07857143 0.09428571]
RESULT SUBMISSION:<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
 for max_depth = 21 for n_estimators=700
[0.14285714 0.16142857 0.07       ... 0.10857143 0.09285714 0.09285714]
RESULT SUBMISSION:Competition / competición: 6aQ6IxU7Va - gini = 0.48438756365585633 for max_depth = 21 for n_estimators=700
[0.12       0.12714286 0.05857143 ... 0.1        0.08714286 0.09142857]
RESULT SUBMISSION:Competition / competición: 6aQ6IxU7Va - gini = 0.4906353108623924 for max_depth = 21 for n_estimators=700
[0.13285714 0.13714286 0.05142857 ... 0.08428571 0.09285714 0.07714286]
RESULT SUBMISSION:Competition / competición: 6aQ6IxU7Va - gini = 0.4929262285233691 for max_depth = 21 for n_estimators=700
[0.13142857 0.12857143 0.05571429 ... 0.11285714 0.10142857 0.07142857]
RESULT SUBMISSION:Competition / competición: 6aQ6IxU7Va - gini = 0.48486931487352014 for max_depth = 21 for n_estimators=700
[0.13428571 0.13142857 0.06285714 ... 0.08714286 0.09285714 0.09428571]
RESULT SUBMISSION:Competition / competición: 6aQ6IxU7Va - gini = 0.49521483562694657 for max_depth = 21 for n_estimators=700
[0.15       0.14571429 0.06285714 ... 0.11       0.08714286 0.09714286]
RESULT SUBMISSION:Competition / competición: 6aQ6IxU7Va - gini = 0.4964602260649358 for max_depth = 21 for n_estimators=700
[0.15714286 0.14142857 0.06857143 ... 0.09857143 0.09857143 0.07857143]
RESULT SUBMISSION:Competition / competición: 6aQ6IxU7Va - gini = 0.4865144317415133 for max_depth = 21 for n_estimators=700
[0.15285714 0.12       0.05285714 ... 0.11285714 0.08714286 0.07857143]
RESULT SUBMISSION:Competition / competición: 6aQ6IxU7Va - gini = 0.4876928160149354 for max_depth = 21 for n_estimators=700
[0.18571429 0.14571429 0.05428571 ... 0.10857143 0.07285714 0.08428571]

ConnectionError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))

In [ ]:
print ("STEP 4: ASSESSING THE MODEL...")
# CALCULATING GINI PERFORMANCE ON DEVELOPMENT SAMPLE
from sklearn.metrics import roc_auc_score
gini_score = 2*roc_auc_score(y_train, y_pred)-1
print ("GINI DEVELOPMENT=", gini_score)

WHAT IS GINI?
* watch this video for reference: https://youtu.be/MiBUBVUC8kE